# Generated by Django 4.2.1 on 2023-06-02 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('raiting', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
