# Generated by Django 4.2.1 on 2023-06-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_raiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInPlace',
            fields=[
                ('temp', models.IntegerField(default=0, verbose_name='temperature (C)')),
                ('humidity', models.IntegerField(default=0, verbose_name='humidity (%)')),
                ('pressure', models.IntegerField(default=0, verbose_name='pressure (mmhg)')),
                ('wind_deg', models.IntegerField(default=0, verbose_name='direction (°)')),
                ('wind_speed', models.IntegerField(default=0, verbose_name='speed (m/s)')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.place')),
            ],
        ),
    ]
